databases:
  - name: blossoms
    databaseName: blossoms_owox
    user: blossoms_owox_user

services:
  - type: web
    name: evergreen
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blossoms_owox
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        